### ISSUE TITLE
[Bug]: In "Integer Squaring" lab, the "test_square.py" file has a minor bug.

### ISSUE THREAD

**Issue by Ochirsaikhan** [ProactiveProgrammers/www.proactiveprogrammers.com#17]
### Contact Details

davaajambal01@allegheny.edu

### What bug did you find in a source code example?

```shell
# Add a test case for confirming the correctness of the compute_square_iterative function
# when it is using the square_function as main.compute_square_for
```

### What repair do you suggest for the source code example?

```shell
# Add a test case for confirming the correctness of the compute_square_iterative function
# when it is using the square_function as main.compute_square_while
```

### How do you know that this source code example is a bug?

[Bug]: In "Integer Squaring" lab, the "test_square.py" file has a minor bug in which the "TODO" list is requiring us to write a test case for "compute_square_for" when the test case for that already exists. It should instead ask us to write the test case for "compute_square_while".

### What is the severity of the bug in the source code example?

Not Severe

### What do you like about this web site?

I really like that Proactive Programmers ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gkapfham** [comment]
Hello @Ochirsaikhan, thanks for raising this issue about a `TODO` marker inside of an **engineering effort** called *Integer Squaring** that had an incorrect `TODO` marker. I have resolved this issue, as you can see in this GitHub repository:

https://github.com/ProactiveProgrammers/integer-squaring-starter

Since this issue is resolve, I'm going to close it now. Please re-open if you think that there is a problem still. Thanks!
