### ISSUE TITLE
[Bug]: Incorrect command on the website for the Quadratics Roots engineering effort

### ISSUE THREAD

**Issue by kemandel** [ProactiveProgrammers/www.proactiveprogrammers.com#19]
### What bug did you find in a source code example?

```shell
The command `poetry run python rootfinder --a 1 --b 1 --c 1` is incorrect and gives a missing module error. should instead be `poetry run rootfinder --a 1 --b 1 --c 1`
```

### What repair do you suggest for the source code example?

```shell
The command should instead be `poetry run rootfinder --a 1 --b 1 --c 1`
```

### How do you know that this source code example is a bug?

I can tell that it is a bug because the expected output is not given when the command is run

### What do you like about this web site?

I really like that Proactive Programmers works!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gkapfham** [comment]
Hello @kemandel, thanks for raising this issue about pointing out that there was an extra word in the command to run the `rootfinder` program! I deleted the word and thus have resolved this issue. For the record, I also added line numbers to the source code blocks and referenced those line numbers in the text. Hopefully, this should also make it a little easier to read the larger blocks of source code. While this improvement is not related to your issue I thought you might appreciate this enhancement! :grinning: 

Since this issue will be resolved when I merge a PR with a new feature, I am going to close this issue once the PR is merged.

If you want to track the PR that will accumulate these changes, please view:

https://github.com/ProactiveProgrammers/www.proactiveprogrammers.com/pull/27

If you see that there are unresolved problems related to this issue, please reopen the issue and let me know!

**Comment by gkapfham** [comment]
The PR that fixes this issue has been merged!
