### ISSUE TITLE
[Bug]: Exhastive

### ISSUE THREAD

**Issue by Yanqiao4396** [ProactiveProgrammers/www.proactiveprogrammers.com#25]
### Contact Details

chen02@allegheny.edu

### What happened?

A bug happened! On the 14th line of the "readme" file of the square rooting assignment, the command uses "exhastive" other than "exhaustive", which makes the command useless.

### What did you expect to happen?

We should use "exhaustive" instead of ''exhastive".

### What do you like about this web site?

It's filtered very well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gkapfham** [comment]
Hello @Yanqiao4396, thanks for raising this issue. You are right, the word was spelled incorrectly in the README file. I have spelled it correctly in the starter's GitHub repository, which you can find here:

https://github.com/ProactiveProgrammers/square-roots-starter

Since this issue is resolved, I am going to close it now. If you think that there is still a problem with this README file, please re-open the issue and explain how it was not correctly resolved. Thanks!
